project_id = "ruta100-backend"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = [
  "exp://127.0.0.1:8081",
  "exp://localhost:8081",
  "ruta100://auth/callback"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[edge_runtime]
enabled = true
policy = "oneshot"
